### ISSUE TITLE
Installing in windows

### ISSUE THREAD

**Issue by mukral** [voneiden/ocp-freecad-cam#21]
Hello, has anyone success with running ocp_freecad_cam in a windows (11) environment?

When I run python code I got an error "ModuleNotFoundError: No module named 'FreeCAD'". I've tried a lot...

The installation of ocp_freecad_ cam library with pip looks fine (it's not 1.0.0 but 0.94, but this shouldn't an issue)  

I think the problem is the path for the freecad-libraries:

echo %PYTHONPATH%
showed only itself %PYTHONPATH%

So I used:

set PYTHONPATH=.;%PYTHONPATH%;C:\Users\...\PythonSoftwareFoundation.Python.3.10;C:\Users\...\freecad\FreeCAD_weekly-builds-34651-2023-10-13-conda-Windows-x86_64-py310\lib;C:\Users\...\freecad\FreeCAD_weekly-builds-34651-2023-10-13-conda-Windows-x86_64-py310\Mod\Draft;C:\Users\tux\freecad\FreeCAD_weekly-builds-34651-2023-10-13-conda-Windows-x86_64-py310\Mod\Path

(and many more ;-) ) to add the directories to the Pathvariable. But I even don't know if the python-environment in windows11 the path variable is handled like this. Python environment is installed via windows app store and it works fine with vs code and "standalone" (with all additional installed python modules).

In freecad-zip for windows I cannot find a python site-packages directory, maybe this is a problem.

I'll try on, and post the solution if I get one.
Any help would be appreciated to cut the waste of time.
Thank you
Markus

**Comment by mukral** [comment]
Version with pth-file in directory site-packages did also not work:
C:\Users\...\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\freecad.pth
I've tried with / and \ and all I can think about.

And a lot more.

**Comment by mukral** [comment]
Unfortunatelly open_freecad_cam is not usable with Windows.

**Comment by voneiden** [comment]
Thanks for doing some pioneer work, you're probably the first one to try Windows.

 I can try doing some testing too and report back, but it might take me some days to get to it. We can keep this issue open, if you don't mind.

I imagine it should work on Windows too, but no doubt it can be tricky to get all the stars aligned..

**Comment by voneiden** [comment]
Using native Windows is now briefly documented in the readme: https://github.com/voneiden/ocp-freecad-cam#windows-7z-installation-example
